"""Add chat sessions and messages

Revision ID: 1f31f87352cc
Revises: 29a33d586ecb
Create Date: 2026-03-04 07:07:39.023268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f31f87352cc'
down_revision: Union[str, Sequence[str], None] = '29a33d586ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    schema='aegis_meta'
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role', schema='aegis_meta'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['aegis_meta.chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_session_sequence'),
    schema='aegis_meta'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages', schema='aegis_meta')
    op.drop_table('chat_sessions', schema='aegis_meta')
    # ### end Alembic commands ###
