"""add_worm_audit_and_signatures

Revision ID: 29a33d586ecb
Revises: 74afd38ce207
Create Date: 2026-03-04 02:42:01.973280

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29a33d586ecb'
down_revision: str | Sequence[str] | None = '74afd38ce207'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'compiled_registry_artifacts',
        sa.Column(
            'signature_algo',
            sa.Text(),
            nullable=False,
            server_default=sa.text("'hmac-sha256-v1'"),
        ),
        schema='aegis_meta',
    )
    op.add_column(
        'compiled_registry_artifacts',
        sa.Column('signature_key_id', sa.Text(), nullable=True),
        schema='aegis_meta',
    )
    op.add_column(
        'metadata_audit',
        sa.Column('previous_hash', sa.Text(), nullable=True),
        schema='aegis_meta',
    )
    op.add_column(
        'metadata_audit',
        sa.Column('row_hash', sa.Text(), nullable=False),
        schema='aegis_meta',
    )
    op.add_column(
        'metadata_audit',
        sa.Column('hash_algorithm', sa.Text(), nullable=False),
        schema='aegis_meta',
    )
    op.add_column(
        'metadata_audit',
        sa.Column('key_id', sa.Text(), nullable=True),
        schema='aegis_meta',
    )
    op.create_unique_constraint(
        'uq_metadata_audit_row_hash',
        'metadata_audit',
        ['row_hash'],
        schema='aegis_meta',
    )

    _worm_fn = (
        "CREATE OR REPLACE FUNCTION aegis_meta.prevent_audit_modification()\n"
        "RETURNS TRIGGER AS $$\n"
        "BEGIN\n"
        "    RAISE EXCEPTION 'WORM Violation: aegis_meta.metadata_audit is"
        " append-only. UPDATE/DELETE forbidden.';\n"
        "END;\n"
        "$$ LANGUAGE plpgsql;"
    )
    op.execute(_worm_fn)
    op.execute("""
    CREATE TRIGGER enforce_worm_audit
    BEFORE UPDATE OR DELETE ON aegis_meta.metadata_audit
    FOR EACH ROW EXECUTE FUNCTION aegis_meta.prevent_audit_modification();
    """)
    op.execute(
        "REVOKE UPDATE, DELETE ON aegis_meta.metadata_audit FROM role_aegis_steward;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "GRANT UPDATE, DELETE ON aegis_meta.metadata_audit TO role_aegis_steward;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS enforce_worm_audit ON aegis_meta.metadata_audit;"
    )
    op.execute("DROP FUNCTION IF EXISTS aegis_meta.prevent_audit_modification();")

    op.drop_constraint(
        'uq_metadata_audit_row_hash',
        'metadata_audit',
        schema='aegis_meta',
        type_='unique',
    )
    op.drop_column('metadata_audit', 'key_id', schema='aegis_meta')
    op.drop_column('metadata_audit', 'hash_algorithm', schema='aegis_meta')
    op.drop_column('metadata_audit', 'row_hash', schema='aegis_meta')
    op.drop_column('metadata_audit', 'previous_hash', schema='aegis_meta')
    op.drop_column(
        'compiled_registry_artifacts', 'signature_key_id', schema='aegis_meta'
    )
    op.drop_column(
        'compiled_registry_artifacts', 'signature_algo', schema='aegis_meta'
    )
    # ### end Alembic commands ###
