"""Init aegis_meta metadata schema

Revision ID: 74afd38ce207
Revises:
Create Date: 2026-03-04 01:14:07.005848

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74afd38ce207'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_audit',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Enum(
        'create', 'update', 'approve', 'deploy', 'revoke',
        name='audit_action', schema='aegis_meta'
    ), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='aegis_meta'
    )
    op.create_table('metadata_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('registry_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum(
        'draft', 'pending_review', 'active', 'archived',
        name='version_status', schema='aegis_meta'
    ), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('version_id'),
    schema='aegis_meta'
    )
    op.create_table('compiled_registry_artifacts',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column(
        'artifact_blob',
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    ),
    sa.Column('artifact_hash', sa.Text(), nullable=False),
    sa.Column('compiled_at', sa.DateTime(), nullable=False),
    sa.Column('compiler_version', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(
        ['version_id'], ['aegis_meta.metadata_versions.version_id'],
    ),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('version_id'),
    schema='aegis_meta'
    )
    op.create_table('metadata_tables',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('real_name', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
        ['version_id'], ['aegis_meta.metadata_versions.version_id'],
    ),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('version_id', 'alias', name='uq_table_alias'),
    sa.UniqueConstraint('version_id', 'real_name', name='uq_table_real_name'),
    sa.UniqueConstraint('version_id', 'table_id', name='uq_table_composite_id'),
    schema='aegis_meta'
    )
    op.create_table('metadata_columns',
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('real_name', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('allowed_in_select', sa.Boolean(), nullable=False),
    sa.Column('allowed_in_filter', sa.Boolean(), nullable=False),
    sa.Column('allowed_in_join', sa.Boolean(), nullable=False),
    sa.Column(
        'safety_classification',
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    ),
    sa.ForeignKeyConstraint(
        ['version_id', 'table_id'],
        [
            'aegis_meta.metadata_tables.version_id',
            'aegis_meta.metadata_tables.table_id',
        ],
    ),
    sa.ForeignKeyConstraint(
        ['version_id'], ['aegis_meta.metadata_versions.version_id'],
    ),
    sa.PrimaryKeyConstraint('column_id'),
    sa.UniqueConstraint('version_id', 'column_id', name='uq_col_composite_id'),
    sa.UniqueConstraint('version_id', 'table_id', 'alias', name='uq_col_alias'),
    sa.UniqueConstraint(
        'version_id', 'table_id', 'real_name', name='uq_col_real_name'
    ),
    schema='aegis_meta'
    )
    op.create_table('metadata_relationships',
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('source_table_id', sa.UUID(), nullable=False),
    sa.Column('source_column_id', sa.UUID(), nullable=False),
    sa.Column('target_table_id', sa.UUID(), nullable=False),
    sa.Column('target_column_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum(
        'fk', 'logical', 'denormalized', name='rel_type', schema='aegis_meta'
    ), nullable=False),
    sa.Column('cardinality', sa.Enum(
        '1:1', '1:n', 'n:1', 'n:m', name='cardinality_type', schema='aegis_meta'
    ), nullable=False),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(
        ['version_id', 'source_column_id'],
        [
            'aegis_meta.metadata_columns.version_id',
            'aegis_meta.metadata_columns.column_id',
        ],
    ),
    sa.ForeignKeyConstraint(
        ['version_id', 'target_column_id'],
        [
            'aegis_meta.metadata_columns.version_id',
            'aegis_meta.metadata_columns.column_id',
        ],
    ),
    sa.ForeignKeyConstraint(
        ['version_id'], ['aegis_meta.metadata_versions.version_id'],
    ),
    sa.PrimaryKeyConstraint('relationship_id'),
    schema='aegis_meta'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_relationships', schema='aegis_meta')
    op.drop_table('metadata_columns', schema='aegis_meta')
    op.drop_table('metadata_tables', schema='aegis_meta')
    op.drop_table('compiled_registry_artifacts', schema='aegis_meta')
    op.drop_table('metadata_versions', schema='aegis_meta')
    op.drop_table('metadata_audit', schema='aegis_meta')
    # ### end Alembic commands ###
